from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class VerdictEnum(str, Enum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    UNVERIFIED = "UNVERIFIED"


class RiskLevelEnum(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    CRITICAL = "CRITICAL"


class Source(BaseModel):
    """Web source evidence retrieved from Google Search Grounding."""
    title: str = Field(..., description="Title of the referenced web page.")
    url: str = Field(..., description="Direct HTTPS link to the source article.")
    domain: str = Field(..., description="Domain name of the source (e.g. nobelprize.org).")


class Claim(BaseModel):
    """An atomic factual assertion extracted from the input text and its verification."""
    id: str = Field(..., description="Unique claim identifier (e.g. claim-1).")
    text: str = Field(..., description="The atomic claim text.")
    start_offset: int = Field(..., description="Character start index in the original text.")
    end_offset: int = Field(..., description="Character end index in the original text.")
    verdict: VerdictEnum = Field(..., description="Verification status.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Verification confidence score (0.0 to 1.0).")
    reasoning: str = Field(..., description="Forensic reasoning explaining the verdict.")
    sources: List[Source] = Field(default_factory=list, description="Authoritative web citations.")


class Metrics(BaseModel):
    """Aggregated truthfulness and hallucination metrics."""
    truth_score: float = Field(..., ge=0.0, le=100.0, description="Overall truth score (0-100%).")
    hallucination_risk: RiskLevelEnum = Field(..., description="Risk severity level.")
    total_claims: int = Field(..., ge=0, description="Total atomic claims extracted.")
    supported_count: int = Field(..., ge=0, description="Count of supported claims.")
    contradicted_count: int = Field(..., ge=0, description="Count of contradicted claims.")
    unverified_count: int = Field(..., ge=0, description="Count of unverified claims.")


class MLPrediction(BaseModel):
    """Prediction generated by the local machine learning claim classifier."""
    claim_id: str
    claim_text: str
    predicted_verdict: VerdictEnum
    ml_confidence: float = Field(..., ge=0.0, le=1.0)


class VerificationReport(BaseModel):
    """Complete forensic factuality report."""
    id: str
    analyzed_at: str
    original_text: str
    metrics: Metrics
    claims: List[Claim]
    ml_predictions: List[MLPrediction] = Field(default_factory=list)


class PresetItem(BaseModel):
    """Built-in demo scenario."""
    id: str
    title: str
    description: str
    text: str
    category: str


class HealthResponse(BaseModel):
    """System health check and readiness response."""
    status: str
    uptime_seconds: float
    environment: str
    model: str
    grounding_ready: bool
    ml_model_loaded: bool
